services:
  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sas_automation_db
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/postgresql-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d sas_automation_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - saas_network

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - DATABASE_URL=${DATABASE_URL}
#       - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
#       - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
#     ports:
#       - "3000:3000"
#     depends_on:
#       postgresql:
#         condition: service_healthy
#     networks:
#       - saas_network

# networks:
#   saas_network:
#     driver: bridge